version: '3'

services:
  frontend:
    # 도커 허브 이미지
    image: yjchoi7166/docker-frontend
    # 로컬 머신에 있는 어플리케이션 소스 코드들 매핑
    volumes:
      # 컨테이너 내부에 설치 된 node 패키지 참조
      - /yj-react-app/node_modules
      # 로컬 머신에 있는 소스 코드 매핑 : 로컬 머신 코드:로컬 머신 코드를 참조해야 할 컨테이너 디렉터리
      - ./react-app:/yj-react-app
    # 리액트 버그를 수정하기 위한 코드
    stdin_open: true
  nginx:
    # 컨테이너가 멈춘 경우 항상 재실행
    restart: always
    # 도커 허브 이미지
    image: yjchoi7166/docker-nginx
    # 포트 매핑 : http 80포트를 nginx 기본 포트와 매핑
    ports:
      - "80:80"

  backend:
    # 도커 허브 이미지
    image: yjchoi7166/docker-backend
    container_name: app-nodejs
    # 로컬 머신에 있는 어플리케이션 소스 코드들 매핑
    volumes:
      # 컨테이너 내부에 설치 된 node 패키지 참조
      - /yj-node-app/node_modules
      # 로컬 머신에 있는 소스 코드 매핑 : 로컬 머신 코드:로컬 머신 코드를 참조해야 할 컨테이너 디렉터리
      - ./nodejs-app:/yj-node-app
    # RDS 연결을 위한 환경변수 설정 : 일라스틱 빈스톡에서 설정
    environment: 
      MYSQL_HOST: $MYSQL_HOST 
      MYSQL_USER: $MYSQL_USER 
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT   
