version: '3'

services:
  frontend:
    # 이미지 빌드에 사용할 도커파일 설정
    build:
      # 도커 이미지를 구성하기 위한 파일 및 디렉터리 위치
      context: ./react-app
      # 도커 파일 이름
      dockerfile: Dockerfile.dev
    # 로컬 머신에 있는 어플리케이션 소스 코드들 매핑
    volumes:
      # 컨테이너 내부에 설치 된 node 패키지 참조
      - /yj-react-app/node_modules
      # 로컬 머신에 있는 소스 코드 매핑 : 로컬 머신 코드:로컬 머신 코드를 참조해야 할 컨테이너 디렉터리
      - ./react-app:/yj-react-app
    # 리액트 버그를 수정하기 위한 코드
    stdin_open: true
  nginx:
    # 컨테이너가 멈춘 경우 항상 재실행
    restart: always
    # 이미지 빌드에 사용할 도커파일 설정
    build:
      # 도커 이미지를 구성하기 위한 파일 및 디렉터리 위치
      context: ./nginx
      # 도커 파일 이름
      dockerfile: Dockerfile
    # 포트 매핑 : 로컬 3000포트를 nginx 기본 포트와 매핑
    ports:
      - "3000:80"

  backend:
    # 이미지 빌드에 사용할 도커파일 설정
    build:
      # 도커 이미지를 구성하기 위한 파일 및 디렉터리 위치
      context: ./nodejs-app
      # 도커 파일 이름
      dockerfile: Dockerfile.dev

  mysql:
    # 이미지 빌드에 사용할 도커파일 설정
    build:
      # 도커 이미지를 구성하기 위한 파일 및 디렉터리 위치
      context: ./mysql
      # 도커 파일 이름
      dockerfile: Dockerfile