apiVersion: v1
kind: PersistentVolumeClaim # PVC 생성
metadata:
  name: nfs-pvc 
spec:
  # 어떤 방식으로 사용하는지 정의
  accessModes:
    - ReadWriteMany # 여러 노드가 읽고 쓸 수 있도록 마운트하는 옵션
  resources:
    requests:
      # 요청하는 볼륨 : 동적 볼륨이 아닌 레이블 의미
      storage: 10Mi