server:
  port: 2205

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/springbootReactTutorial
    username: springbootReactTutorialUser
    password: springbootReactTutorialPassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # ddl-auto : none
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: yooneong-choi-jwt-secret-key-for-springboot