version: "3"
services:
  # 레디스 서버 : 애플리케이션에 설정한 레디스 서버 url 이름
  redis-server:
    # 도커 허브에서 다운받을 이미지 이름
    image: "redis"
  nodejs-app:
    # 빌드할 이미지의 Dockerfile 경로
    build: .
    ports:
      # <호스트 포트>:<애플리케이션 포트>
      - "8081:7166"
